---
title: "CARET"
output: html_notebook
---

Let's try to run some ML stuff in R using CARET. Instructions from https://cran.r-project.org/web/packages/caret/vignettes/caret.pdf and also http://topepo.github.io/caret/measuring-performance.html

```{r}
library(caret)
library(mlbench)
data(Sonar)
set.seed(107)
inTrain <- createDataPartition(y = Sonar$Class,
                               ## the outcome data are needed
                               p = .75,
                               ## The percentage of data in the
                               ## training set
                               list = FALSE)
                               ## The format of the results
str(inTrain)
training <- Sonar[ inTrain,]
testing  <- Sonar[-inTrain,]
nrow(training)
nrow(testing)
```

``` {r}
set.seed(123)
ctrl <- trainControl(method = "repeatedcv",
                      repeats = 3,
                     classProbs = TRUE,
                      summaryFunction = twoClassSummary)
plsFit <- train(Class ~ .,
                 data = training,
                 method = "pls",
                 ## Center and scale the predictors for the training
                 ## set and all future samples.
                tuneLength = 15,
                trControl = ctrl,
                metric = "ROC",
                  preProc = c("center", "scale"))
plsFit
```
Now we try more things
```{r}
plsClasses <- predict(plsFit, newdata = testing)
str(plsClasses)
plsProbs <- predict(plsFit, newdata = testing, type = "prob")
confusionMatrix(data = plsClasses, testing$Class)
```
We can try a different model:
```{r}
rdaGrid = data.frame(gamma = (0:4)/4, lambda = 3/4)
set.seed(123)
rdaFit <- train(Class ~ .,
                 data = training,
                 method = "rda",
                 tuneGrid = rdaGrid,
                 trControl = ctrl,
                 metric = "ROC")
rdaFit
```

Results

```{r}
rdaClasses <- predict(rdaFit, newdata = testing)
confusionMatrix(rdaClasses, testing$Class)
```
Comparing resampling results:
```{r}
resamps <- resamples(list(pls = plsFit, rda = rdaFit))
summary(resamps)
```

More

```{r}
summary(diff(resamps))
xyplot(resamps, what = "BlandAltman")
```


