---
title: "Analysis of structural data"
output: html_notebook
---

Now we do some classification using DX and structural data. First, some data cleaning:

```{r}
# for replication purposes
set.seed(107)
source('~/ncr_notebooks/baseline_prediction//src/aux_functions.R')

# Philip pre-selected which structural scans to use
gf_fname = '~/data/baseline_prediction/structural_match_02092017.csv'
data_fname = '~/data/baseline_prediction/structural_long_02092017.csv'
gf = read.csv(gf_fname)
group_var = 'DX_A'
data = read.csv(data_fname)
maskid_gf = unique(gf[, c('MASKID', group_var)])

ldata = merge(maskid_gf, data, by.x='MASKID', by.y='lh.aparc.thickness', all.y = F)
eval(parse(text=sprintf('groups = ldata$\"%s\"', group_var)))
idx = groups=='NV' | groups=='ADHD'
groups = factor(groups[idx])
ldata = ldata[idx,]
```

As usual, let's start by throwing everything in there, and then start doing it by domains:

```{r}
phen_vars = c(which(grepl("_thickness$", colnames(ldata))),
              which(grepl("_volume$", colnames(ldata))),
              which(grepl("_area$", colnames(ldata))),
              which(grepl("^Left.", colnames(ldata))),
              which(grepl("^Right.", colnames(ldata)))
              )
# remove WM variables
idx = phen_vars < 261 | phen_vars > 266 
phen_vars = phen_vars[idx]
ldata = ldata[, phen_vars]

```

```{r}
# leaving this just for examples, but we actually run it in the cluster and collect it later
ncv = 5
nrepeatcv = 2
nsplits = 5
train_test_ratio = .85
root_fname = '~/tmp/struct_NVvsADHD_all'
# saving output
library(caret)
sink(sprintf('%s.log', root_fname), append=FALSE, split=TRUE)
# ncores = detectCores(all.tests = FALSE, logical = TRUE)
ncpus <- detectBatchCPUs()
njobs = ncpus - 2

run_models = c('xgb') #c('rndForest', 'lr', 'lsvm', 'rsvm', 'xgb', 'gbm')

inTrain = createDataPartition(y = groups,
                              times= nsplits,
                              p=train_test_ratio)
metric = "ROC"
default_preproc = c("center", 'scale')
default_options = c()
ctrl_cv <- trainControl(method = "repeatedcv",
                        number = ncv,
                        repeats = nrepeatcv,
                        classProbs = TRUE,
                        returnData = FALSE,
                        summaryFunction = twoClassSummary,
                        preProcOptions = default_options,
                        search='grid')

source('~/ncr_notebooks/baseline_prediction/src/do_classification.R')

```
Let's plot different metrics on the test data.

#All data

```{r}
root_dir = '~/data/baseline_prediction/results/'
root_fname = 'struct_NVvsADHD_all'
source('~/ncr_notebooks/baseline_prediction/src/collect_results.R')
source('~/ncr_notebooks/baseline_prediction/src/do_metrics_plots.R')
```
#All data, PCA

```{r}
root_dir = '~/data/baseline_prediction/results/'
root_fname = 'struct_NVvsADHD_all_pca'
source('~/ncr_notebooks/baseline_prediction/src/collect_results.R')
source('~/ncr_notebooks/baseline_prediction/src/do_metrics_plots.R')
```
#Cortical thickness

```{r}
ldata = merge(maskid_gf, data, by.x='MASKID', by.y='lh.aparc.thickness', all.y = F)
eval(parse(text=sprintf('groups = ldata$\"%s\"', group_var)))
idx = groups=='NV' | groups=='ADHD'
groups = factor(groups[idx])
ldata = ldata[idx,]
phen_vars = which(grepl("_thickness$", colnames(ldata)))
# remove WM variables
idx = phen_vars < 261 | phen_vars > 266 
phen_vars = phen_vars[idx]
ldata = ldata[, phen_vars]

root_fname = 'struct_NVvsADHD_corticalThickness'
source('~/ncr_notebooks/baseline_prediction/src/collect_results.R')
source('~/ncr_notebooks/baseline_prediction/src/do_metrics_plots.R')
```

#Cortical thickness, PCA

```{r}
root_fname = 'struct_NVvsADHD_corticalThickness_pca'
source('~/ncr_notebooks/baseline_prediction/src/collect_results.R')
source('~/ncr_notebooks/baseline_prediction/src/do_metrics_plots.R')
```

#Cortical area

```{r}
ldata = merge(maskid_gf, data, by.x='MASKID', by.y='lh.aparc.thickness', all.y = F)
eval(parse(text=sprintf('groups = ldata$\"%s\"', group_var)))
idx = groups=='NV' | groups=='ADHD'
groups = factor(groups[idx])
ldata = ldata[idx,]
phen_vars = which(grepl("_area$", colnames(ldata)))
# remove WM variables
idx = phen_vars < 261 | phen_vars > 266 
phen_vars = phen_vars[idx]
ldata = ldata[, phen_vars]

root_fname = 'struct_NVvsADHD_corticalArea'
source('~/ncr_notebooks/baseline_prediction/src/collect_results.R')
source('~/ncr_notebooks/baseline_prediction/src/do_metrics_plots.R')
```

#Cortical area, PCA

```{r}
root_fname = 'struct_NVvsADHD_corticalArea_pca'
source('~/ncr_notebooks/baseline_prediction/src/collect_results.R')
source('~/ncr_notebooks/baseline_prediction/src/do_metrics_plots.R')
```

#Cortical Volume

```{r}
ldata = merge(maskid_gf, data, by.x='MASKID', by.y='lh.aparc.thickness', all.y = F)
eval(parse(text=sprintf('groups = ldata$\"%s\"', group_var)))
idx = groups=='NV' | groups=='ADHD'
groups = factor(groups[idx])
ldata = ldata[idx,]
phen_vars = which(grepl("_volume$", colnames(ldata)))
# remove WM variables
idx = phen_vars < 261 | phen_vars > 266 
phen_vars = phen_vars[idx]
ldata = ldata[, phen_vars]

root_fname = 'struct_NVvsADHD_corticalVolume'
source('~/ncr_notebooks/baseline_prediction/src/collect_results.R')
source('~/ncr_notebooks/baseline_prediction/src/do_metrics_plots.R')
```

#Cortical Volume, PCA

```{r}
root_fname = 'struct_NVvsADHD_corticalVolume_pca'
source('~/ncr_notebooks/baseline_prediction/src/collect_results.R')
source('~/ncr_notebooks/baseline_prediction/src/do_metrics_plots.R')
```




